version: '3.8'
services:
  codechecker:
    image: codechecker/codechecker-web
    environment:
      DATABASE: postgres
      POSTGRES_USER: codechecker
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: codechecker
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: codecheckerdb
    volumes:
      - ./data:/var/lib/postgresql/data
